### ISSUE TITLE
Inputbox does not work if I set groupingSeparator as "." and fractionSeparator as ","

### ISSUE THREAD

**Issue by ashishmangukiya** [AleksandrNikolaevich/react-native-money-input#4]
<MoneyTextInput
                    autoFocus={true}
                    placeholderTextColor='rgba(0, 0, 0, 0.6)'
                    value={entry.amount}
                    style={[
                      {
                        fontFamily: 'Archivo-Bold',
                        fontSize: 26,
                        ...(Platform.OS == 'android' ? { lineHeight: 32 } : null),
                        paddingVertical: 2,
                        textAlignVertical: 'top',
                        letterSpacing: 0.6,
                        color: type == 'income' ? 'green' : 'red',
                        flex: 1,
                      },
                    ]}
                    onChangeText={(formatted, text) => {
                      setEntry({ ...entry, amount: text });
                    }}
                    groupingSeparator={'.'}
                    fractionSeparator={','}
                    keyboardType={Platform.select({ ios: 'decimal-pad', android: 'numeric' })}
                    allowFontScaling={false}
                  />

The format is required for European users - 123.456,78

https://github.com/user-attachments/assets/3e4044e6-6f58-4234-a252-9934be3ebf1f

**Comment by ashishmangukiya** [comment]
Hi @AleksandrNikolaevich, just today I thought to try the library, and so far it's working great except the one scenario.

**Comment by AleksandrNikolaevich** [comment]
Hi @ashishmangukiya I'll check this bug on this weekend. But I need more info.

- React Native version
- Is the new arch enabled?
- Your simulator's language and region settings (see screenshot below)


<img width="1264" height="2296" alt="Image" src="https://github.com/user-attachments/assets/1b02676f-8e1d-49a8-9708-990396a74bed" />

**Comment by ashishmangukiya** [comment]
@AleksandrNikolaevich, thanks for the quick response.

React Native version - 0.81.4
Is the new arch enabled - yes

<img width="1320" height="2868" alt="Image" src="https://github.com/user-attachments/assets/6001b7cc-e259-4517-9965-707d9284efd0" />

I even tried changing the number format from the simulator/real device settings to 12.34.567,89, but still the same issue.

 below)

**Comment by ashishmangukiya** [comment]
Working all the formats like '123,456.78', '123 456,78', "123'456.78", '1,23,456.78' but not '123.456,78'
The issue may be because of "."?

**Comment by AleksandrNikolaevich** [comment]
Hi @ashishmangukiya, the fix has been published. 
See version [v0.5.0](https://github.com/AleksandrNikolaevich/react-native-money-input/releases/tag/v0.5.0).

Please check, hope the problem is solved!

if possible, please star this project and recommend it

**Comment by ashishmangukiya** [comment]
HI @AleksandrNikolaevich  
Thanks for releasing the new version. I really appreciate your efforts.
I have updated the library version to 0.5.0, but still the same issue 

  <MoneyTextInput
                    placeholderTextColor='rgba(0, 0, 0, 0.6)'
                    value={entry.amount}
              
                    onChangeText={(formatted, extracted) => setEntry({ ...entry, amount: extracted })}
                    keyboardType='numeric'
                    allowFontScaling={false}
                    groupingSeparator={'.'}
                    fractionSeparator={','}
                  />


https://github.com/user-attachments/assets/f4dedd3a-e56e-4a56-a248-6f54e4e04183

**Comment by ashishmangukiya** [comment]
HI @AleksandrNikolaevich 
I found the issue: if I pass prefix as {' '} or {'$'}, it works fine, but if I don’t pass the prop at all, it doesn’t work, so please test without the prefix prop and 
groupingSeparator={'.'}
fractionSeparator={','}
You can reproduce the issue in the above way.

**Comment by AleksandrNikolaevich** [comment]
@ashishmangukiya I haven't checked this case 🤦
Now, I hope all the problems are solved.

[v0.5.1](https://github.com/AleksandrNikolaevich/react-native-money-input/releases/tag/v0.5.1) has published

https://github.com/user-attachments/assets/3f8385da-bc7d-414f-969f-2aa2351de2d2

**Comment by ashishmangukiya** [comment]
Yes, now everything works smooth 👍
